# Generated by Django 6.0.1 on 2026-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='office_location',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
